exports.SOCKET_EVENT = {
  VIEWER_STATUS: {
    PDF_LOAD_SUCCESS: 'PDF_LOAD_SUCCESS',
    PDF_LOAD_FAIL: 'PDF_LOAD_FAIL',
    VIEWER_IDLE: 'VIEWER_IDLE'
  },
  FILE_INDEX: {
    SET_FILE_INDEX: 'SET_FILE_INDEX',
    GET_FILE: 'GET_FILE',
    GET_LATEST_FILE: 'GET_LATEST_FILE'
  },
  PAGE_ACTIONS: {
    SET_NEXT_PAGE: 'SET_NEXT_PAGE',
    SET_PREV_PAGE: 'SET_PREV_PAGE'
  }
}
